/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.onemillionworlds;

import com.onemillionworlds.tasks.TypedJarMaterials;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.SourceSetContainer;
import  com.onemillionworlds.configuration.TypedMaterialsExtension;

import java.io.File;

public class TypedMaterialsPlugin implements Plugin<Project> {
    public static final String DEFAULT_GENERATED_SOURCES_DIR = "src/main/generated/java";

    public void apply(Project project) {

        TypedMaterialsExtension extension = project.getExtensions().create("typedMaterials", TypedMaterialsExtension.class, project);

        String sourcesRoot = extension.getGeneratedSourcesDir();

        extension.getConfigurations().all(configuration -> {
            String taskName = configuration.getName() + "TypedMaterials";

            project.getTasks().register(taskName, TypedJarMaterials.class, task -> {
                task.setOutputPackage(configuration.getOutputPackage());
                task.setOutputSourcesRoot(project.file(sourcesRoot));
                task.setJarFilterRegex(configuration.getJarFilterRegex());
            });
            project.getTasks().named("compileJava").configure(compileJava -> {
                compileJava.dependsOn(taskName);
            });
        });

        // Add 'src/main/generated/java' to sourceSets.main.java.srcDirs
        project.afterEvaluate(p -> {
            SourceSetContainer sourceSets = project.getExtensions().getByType(SourceSetContainer.class);
            SourceSet mainSourceSet = sourceSets.getByName(SourceSet.MAIN_SOURCE_SET_NAME);
            File generatedSourcesDir = project.file(sourcesRoot);

            if (!mainSourceSet.getJava().getSrcDirs().contains(generatedSourcesDir)) {
                mainSourceSet.getJava().srcDir(generatedSourcesDir);
            }
        });
    }
}
