package com.onemillionworlds.tasks;

import com.onemillionworlds.tasks.assets.AssetsFolder;
import org.gradle.api.DefaultTask;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.file.FileCollection;
import org.gradle.api.file.RegularFile;
import org.gradle.api.model.ObjectFactory;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.Provider;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.InputFiles;
import org.gradle.api.tasks.Internal;
import org.gradle.api.tasks.Optional;
import org.gradle.api.tasks.OutputFile;
import org.gradle.api.tasks.PathSensitive;
import org.gradle.api.tasks.PathSensitivity;
import org.gradle.api.tasks.TaskAction;
import org.gradle.work.DisableCachingByDefault;

import javax.inject.Inject;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

@DisableCachingByDefault(because = "Generates source files directly into the project; quicker to regenerate than to fetch from a cache")
public class AssetConstants extends DefaultTask{

    public static final String FLAT_FILE_CONTEXT_CHANGE = "::";
    public static final String ASSETS_FILE_NAME = "com_onemillionworlds_typedmaterials_assets.txt";

    private static final String classTemplate = """
                                     package [PACKAGE];

                                     /**
                                      * AUTOGENERATED CLASS, do not modify
                                      * <p>
                                      * Generated by the Typed Materials plugin. For more information:
                                      * </p>
                                      * @see <a href="https://github.com/oneMillionWorlds/TypedMaterials/wiki">MaterialTyper Plugin Wiki</a>
                                      */
                                     @SuppressWarnings("all")
                                     public class [CLASS] {

                                     [CONTENT]

                                     }""";

    /**
     * If present, use this as the class name for the Assets constants class
     */
    private final Property<String> fullyQualifiedAssetsClass;

    /**
     * If present use this as a regex to defermine if a jar should be fully searched for assets.
     * (This means going through every file in the jar, not using the flat file that helpful libraries may
     * leave in the jar)
     */
    private final Property<String> jarFilterRegex;

    /**
     * If present, use this regex to filter the files within the jars, only those that match will be included
     */
    private final Property<String> withinJarFileRegex;

    /**
     * If present, use this sources root to output all the assets as a java class
     */
    private final DirectoryProperty outputSourcesRoot;

    /**
     * If present, use this resources root to output all the assets as a flat file
     */
    private final DirectoryProperty outputResourcesRoot;

    /**
     * If present, will use these files
     */
    private final ConfigurableFileCollection assetFlatFiles;

    /**
     * The local resource directories to search for assets. By default, the plugin sets this to the main resource
     * directories.
     */
    private final ConfigurableFileCollection resourceDirectories;

    /**
     * The name of the project owning this task, used as the context in the flat file. By default, the plugin sets
     * this to the project name.
     */
    private final Property<String> projectName;

    /**
     * The classpath whose jars will be searched when a jarFilterRegex is set. When registering this task manually
     * (rather than via the typedMaterials extension) this should be set to the runtimeClasspath configuration.
     */
    private final ConfigurableFileCollection runtimeClasspath;

    @Inject
    public AssetConstants(ObjectFactory objects){
        fullyQualifiedAssetsClass = objects.property(String.class);
        jarFilterRegex = objects.property(String.class);
        withinJarFileRegex = objects.property(String.class);
        outputSourcesRoot = objects.directoryProperty();
        outputResourcesRoot = objects.directoryProperty();
        assetFlatFiles = objects.fileCollection();
        resourceDirectories = objects.fileCollection();
        projectName = objects.property(String.class);
        runtimeClasspath = objects.fileCollection();
    }

    @TaskAction
    public void createTypedMaterials(){
        AssetsFolder assetsFolder = new AssetsFolder("");

        for(File folder : resourceDirectories){
            assetsFolder.addAll(searchForAllFiles(folder, "", null));
        }

        AssetsFolder resourcesFolderFast = searchAllFromSuppliedFlatFiles();
        assetsFolder.addAll(resourcesFolderFast);

        if(jarFilterRegex.isPresent() && !jarFilterRegex.get().isBlank()){
            AssetsFolder jarAssets = searchAllFromJars(jarFilterRegex.get());
            assetsFolder.addAll(jarAssets);
        }

        try {
            if(getDestinationFile().isPresent()){
                String classContent = assetsFolder.getJavaClassContent(1, List.of(getClassName()));

                String fullClass = classTemplate
                        .replace("[PACKAGE]", getDestinationPackage())
                        .replace("[CLASS]", getClassName())
                        .replace("[CONTENT]", classContent);
                Files.writeString(getDestinationFile().get().getAsFile().toPath(), fullClass);
            }
            if(getDestinationFlatFile().isPresent()){
                String flatFileStringBuilder = FLAT_FILE_CONTEXT_CHANGE + projectName.getOrElse("") + "\n" +
                        assetsFolder.getFileListingContent();
                Files.writeString(getDestinationFlatFile().get().getAsFile().toPath(), flatFileStringBuilder);
            }
        } catch (Exception e) {
            throw new RuntimeException("Error writing record of generation: " + getName() + ". " + e.getMessage(), e);
        }
    }

    private AssetsFolder searchAllFromJars(String jarFilterRegex){
        Pattern pattern = Pattern.compile(jarFilterRegex);

        Pattern withinJarPattern = Pattern.compile(withinJarFileRegex.getOrElse(".*"));

        Set<File> resolve = runtimeClasspath.getFiles();

        if (resolve.isEmpty()){
            getLogger().warn("Task " + getPath() + " has a jarFilterRegex but no runtimeClasspath to search");
        }

        AssetsFolder assetsFolder = new AssetsFolder("");
        resolve.forEach(file -> {
            if (file.getName().endsWith(".jar") && pattern.matcher(file.getName()).matches()) {
                String context = file.getName().replace(".jar", "");

                try (ZipInputStream zip = new ZipInputStream(new FileInputStream(file))) {
                    ZipEntry entry;
                    while ((entry = zip.getNextEntry()) != null) {
                        if(entry.isDirectory()){
                            continue;
                        }
                        if(entry.getName().endsWith(".class")){
                            continue;
                        }
                        if(!withinJarPattern.matcher(entry.getName()).matches()){
                            continue;
                        }

                        assetsFolder.addAssetFromFullRelativePath(entry.getName(), context);
                        zip.closeEntry();
                    }
                } catch (Exception e) {
                    throw new RuntimeException("Error processing JAR: " + file + e.getMessage(), e);
                }
            }
        });
        return assetsFolder;
    }

    private AssetsFolder searchForAllFiles(File file, String currentPath, String context){

        AssetsFolder assetsFolder = new AssetsFolder(currentPath);

        File[] files = file.listFiles();

        if(files==null){
            return assetsFolder;
        }

        for( File fileToProcess : Arrays.stream(files).sorted().toList()){
            if (fileToProcess.isFile()){
                assetsFolder.addAsset(new AssetsFolder.AssetItem(fileToProcess.getName(), context));
            }else{
                AssetsFolder subFolder = searchForAllFiles(fileToProcess, currentPath + (currentPath.isBlank()?"":"/") + fileToProcess.getName(), context);
                assetsFolder.addSubfolder(fileToProcess.getName(), subFolder);
            }
        }

        return assetsFolder;
    }

    private AssetsFolder searchAllFromSuppliedFlatFiles(){
        AssetsFolder assetsFolder = new AssetsFolder("");

        assetFlatFiles.forEach(file -> {
            try {
                List<String> lines = Files.readAllLines(file.toPath());
                assetsFolder.addAssetsFromFlatFile(lines);
            } catch (IOException e) {
                throw new RuntimeException("Error reading flat file: " + file, e);
            }
        });
        return assetsFolder;
    }

    @Optional
    @Input
    public Property<String> getFullyQualifiedAssetsClass(){
        return fullyQualifiedAssetsClass;
    }

    public void setFullyQualifiedAssetsClass(String fullyQualifiedAssetsClass){
        this.fullyQualifiedAssetsClass.set(fullyQualifiedAssetsClass);
    }

    @Optional
    @Input
    public Property<String> getJarFilterRegex(){
        return jarFilterRegex;
    }

    public void setJarFilterRegex(String jarFilterRegex){
        this.jarFilterRegex.set(jarFilterRegex);
    }

    @Optional
    @Input
    public Property<String> getWithinJarFileRegex(){
        return withinJarFileRegex;
    }

    public void setWithinJarFileRegex(String withinJarFileRegex){
        this.withinJarFileRegex.set(withinJarFileRegex);
    }

    @InputFiles
    @PathSensitive(PathSensitivity.RELATIVE)
    public ConfigurableFileCollection getResourceDirectories(){
        return resourceDirectories;
    }

    @InputFiles
    @PathSensitive(PathSensitivity.NONE)
    public ConfigurableFileCollection getAssetFlatFiles() {
        return assetFlatFiles;
    }

    public void setAssetFlatFiles(FileCollection assetFlatFiles) {
        this.assetFlatFiles.setFrom(assetFlatFiles);
    }

    @Optional
    @Input
    public Property<String> getProjectName(){
        return projectName;
    }

    public void setProjectName(String projectName){
        this.projectName.set(projectName);
    }

    /**
     * Jar names are significant (they are used for filtering and as the context), so this is NAME_ONLY rather than
     * a @Classpath
     */
    @InputFiles
    @PathSensitive(PathSensitivity.NAME_ONLY)
    public ConfigurableFileCollection getRuntimeClasspath(){
        return runtimeClasspath;
    }

    public void setRuntimeClasspath(FileCollection runtimeClasspath){
        this.runtimeClasspath.setFrom(runtimeClasspath);
    }

    @Internal
    public DirectoryProperty getOutputSourcesRoot(){
        return outputSourcesRoot;
    }

    public void setOutputSourcesRoot(File outputSourcesRoot){
        this.outputSourcesRoot.set(outputSourcesRoot);
    }

    @Internal
    public DirectoryProperty getOutputResourcesRoot(){
        return outputResourcesRoot;
    }

    public void setOutputResourcesRoot(File outputResourcesRoot){
        this.outputResourcesRoot.set(outputResourcesRoot);
    }

    @Optional
    @OutputFile
    public Provider<RegularFile> getDestinationFile(){
        return outputSourcesRoot.file(fullyQualifiedAssetsClass.map(fqcn -> fqcn.replace(".", "/") + ".java"));
    }

    @Optional
    @OutputFile
    public Provider<RegularFile> getDestinationFlatFile(){
        return outputResourcesRoot.file(ASSETS_FILE_NAME);
    }

    private String getDestinationPackage(){
        return fullyQualifiedAssetsClass.get()
                .replaceAll("\\.[A-Za-z0-9_]+$", "");
    }

    private String getClassName(){
        return fullyQualifiedAssetsClass.get()
                .replaceAll(".*\\.", "");
    }
}
