package com.onemillionworlds.tasks;

import com.onemillionworlds.tasks.assets.AssetsFolder;
import org.gradle.api.DefaultTask;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.file.RegularFile;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.Provider;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.InputFiles;
import org.gradle.api.tasks.Internal;
import org.gradle.api.tasks.Optional;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.PathSensitive;
import org.gradle.api.tasks.PathSensitivity;
import org.gradle.api.tasks.TaskAction;
import org.gradle.work.DisableCachingByDefault;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

@DisableCachingByDefault(because = "Generation is cheap; quicker to regenerate than to fetch from a cache")
public abstract class AssetConstants extends DefaultTask{

    public static final String FLAT_FILE_CONTEXT_CHANGE = "::";
    public static final String ASSETS_FILE_NAME = "com_onemillionworlds_typedmaterials_assets.txt";

    private static final String classTemplate = """
                                     package [PACKAGE];

                                     /**
                                      * AUTOGENERATED CLASS, do not modify
                                      * <p>
                                      * Generated by the Typed Materials plugin. For more information:
                                      * </p>
                                      * @see <a href="https://github.com/oneMillionWorlds/TypedMaterials/wiki">MaterialTyper Plugin Wiki</a>
                                      */
                                     @SuppressWarnings("all")
                                     public class [CLASS] {

                                     [CONTENT]

                                     }""";

    /**
     * If present, use this as the class name for the Assets constants class
     */
    @Optional
    @Input
    public abstract Property<String> getFullyQualifiedAssetsClass();

    /**
     * If present use this as a regex to determine if a jar should be fully searched for assets.
     * (This means going through every file in the jar, not using the flat file that helpful libraries may
     * leave in the jar)
     */
    @Optional
    @Input
    public abstract Property<String> getJarFilterRegex();

    /**
     * If present, use this regex to filter the files within the jars, only those that match will be included
     */
    @Optional
    @Input
    public abstract Property<String> getWithinJarFileRegex();

    /**
     * The local resource directories to search for assets. By default, the plugin sets this to the main resource
     * directories.
     */
    @InputFiles
    @PathSensitive(PathSensitivity.RELATIVE)
    public abstract ConfigurableFileCollection getResourceDirectories();

    /**
     * Asset flat files (e.g. produced by the assetsFile task of other modules) whose assets should be included
     */
    @InputFiles
    @PathSensitive(PathSensitivity.NONE)
    public abstract ConfigurableFileCollection getAssetFlatFiles();

    /**
     * The name of the project owning this task, used as the context in the flat file. By default, the plugin sets
     * this to the project name.
     */
    @Optional
    @Input
    public abstract Property<String> getProjectName();

    /**
     * The classpath whose jars will be searched when a jarFilterRegex is set. When registering this task manually
     * (rather than via the typedMaterials extension) this should be set to the runtimeClasspath configuration.
     * <p>
     * Jar names are significant (they are used for filtering and as the context), so this is NAME_ONLY rather than
     * a @Classpath
     * </p>
     */
    @InputFiles
    @PathSensitive(PathSensitivity.NAME_ONLY)
    public abstract ConfigurableFileCollection getRuntimeClasspath();

    /**
     * If present, the assets are output as a java class into this directory. It should not be shared with any other
     * task.
     */
    @Optional
    @OutputDirectory
    public abstract DirectoryProperty getOutputSourcesRoot();

    /**
     * If present, the assets are output as a flat file into this directory. It should not be shared with any other
     * task.
     */
    @Optional
    @OutputDirectory
    public abstract DirectoryProperty getOutputResourcesRoot();

    @TaskAction
    public void createTypedMaterials(){
        AssetsFolder assetsFolder = new AssetsFolder("");

        for(File folder : getResourceDirectories()){
            assetsFolder.addAll(searchForAllFiles(folder, "", null));
        }

        AssetsFolder resourcesFolderFast = searchAllFromSuppliedFlatFiles();
        assetsFolder.addAll(resourcesFolderFast);

        if(getJarFilterRegex().isPresent() && !getJarFilterRegex().get().isBlank()){
            AssetsFolder jarAssets = searchAllFromJars(getJarFilterRegex().get());
            assetsFolder.addAll(jarAssets);
        }

        try {
            if(getDestinationFile().isPresent()){
                String classContent = assetsFolder.getJavaClassContent(1, List.of(getClassName()));

                String fullClass = classTemplate
                        .replace("[PACKAGE]", getDestinationPackage())
                        .replace("[CLASS]", getClassName())
                        .replace("[CONTENT]", classContent);
                Path destination = getDestinationFile().get().getAsFile().toPath();
                Files.createDirectories(destination.getParent());
                Files.writeString(destination, fullClass);
            }
            if(getDestinationFlatFile().isPresent()){
                String flatFileStringBuilder = FLAT_FILE_CONTEXT_CHANGE + getProjectName().getOrElse("") + "\n" +
                        assetsFolder.getFileListingContent();
                Path destination = getDestinationFlatFile().get().getAsFile().toPath();
                Files.createDirectories(destination.getParent());
                Files.writeString(destination, flatFileStringBuilder);
            }
        } catch (Exception e) {
            throw new RuntimeException("Error writing record of generation: " + getName() + ". " + e.getMessage(), e);
        }
    }

    private AssetsFolder searchAllFromJars(String jarFilterRegex){
        Pattern pattern = Pattern.compile(jarFilterRegex);

        Pattern withinJarPattern = Pattern.compile(getWithinJarFileRegex().getOrElse(".*"));

        Set<File> resolve = getRuntimeClasspath().getFiles();

        if (resolve.isEmpty()){
            getLogger().warn("Task " + getPath() + " has a jarFilterRegex but no runtimeClasspath to search");
        }

        AssetsFolder assetsFolder = new AssetsFolder("");
        resolve.forEach(file -> {
            if (file.getName().endsWith(".jar") && pattern.matcher(file.getName()).matches()) {
                String context = file.getName().replace(".jar", "");

                try (ZipInputStream zip = new ZipInputStream(new FileInputStream(file))) {
                    ZipEntry entry;
                    while ((entry = zip.getNextEntry()) != null) {
                        if(entry.isDirectory()){
                            continue;
                        }
                        if(entry.getName().endsWith(".class")){
                            continue;
                        }
                        if(!withinJarPattern.matcher(entry.getName()).matches()){
                            continue;
                        }

                        assetsFolder.addAssetFromFullRelativePath(entry.getName(), context);
                        zip.closeEntry();
                    }
                } catch (Exception e) {
                    throw new RuntimeException("Error processing JAR: " + file + e.getMessage(), e);
                }
            }
        });
        return assetsFolder;
    }

    private AssetsFolder searchForAllFiles(File file, String currentPath, String context){

        AssetsFolder assetsFolder = new AssetsFolder(currentPath);

        File[] files = file.listFiles();

        if(files==null){
            return assetsFolder;
        }

        for( File fileToProcess : Arrays.stream(files).sorted().toList()){
            if (fileToProcess.isFile()){
                assetsFolder.addAsset(new AssetsFolder.AssetItem(fileToProcess.getName(), context));
            }else{
                AssetsFolder subFolder = searchForAllFiles(fileToProcess, currentPath + (currentPath.isBlank()?"":"/") + fileToProcess.getName(), context);
                assetsFolder.addSubfolder(fileToProcess.getName(), subFolder);
            }
        }

        return assetsFolder;
    }

    private AssetsFolder searchAllFromSuppliedFlatFiles(){
        AssetsFolder assetsFolder = new AssetsFolder("");

        getAssetFlatFiles().forEach(file -> {
            try {
                List<String> lines = Files.readAllLines(file.toPath());
                assetsFolder.addAssetsFromFlatFile(lines);
            } catch (IOException e) {
                throw new RuntimeException("Error reading flat file: " + file, e);
            }
        });
        return assetsFolder;
    }

    @Internal
    public Provider<RegularFile> getDestinationFile(){
        return getOutputSourcesRoot().file(getFullyQualifiedAssetsClass().map(fqcn -> fqcn.replace(".", "/") + ".java"));
    }

    @Internal
    public Provider<RegularFile> getDestinationFlatFile(){
        return getOutputResourcesRoot().file(ASSETS_FILE_NAME);
    }

    private String getDestinationPackage(){
        return getFullyQualifiedAssetsClass().get()
                .replaceAll("\\.[A-Za-z0-9_]+$", "");
    }

    private String getClassName(){
        return getFullyQualifiedAssetsClass().get()
                .replaceAll(".*\\.", "");
    }
}
