package com.onemillionworlds.configuration;

import com.onemillionworlds.TypedMaterialsPlugin;
import com.onemillionworlds.tasks.AssetConstants;
import com.onemillionworlds.tasks.MaterialFactoryTask;
import com.onemillionworlds.tasks.TypedJarMaterials;
import com.onemillionworlds.tasks.TypedLocalMaterials;
import org.gradle.api.Project;
import org.gradle.api.Task;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.file.ProjectLayout;
import org.gradle.api.model.ObjectFactory;
import org.gradle.api.plugins.JavaPlugin;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.SourceSetContainer;
import org.gradle.api.tasks.TaskProvider;

import java.util.function.Function;

@SuppressWarnings("unused")
public class TypedMaterialsExtension{

    private final Project project;

    /**
     * The directory under which generated sources are placed (each task generates into its own subdirectory).
     */
    private final DirectoryProperty generatedSourcesDirectory;

    /**
     * The directory under which generated resources are placed (each task generates into its own subdirectory).
     */
    private final DirectoryProperty generatedResourcesDirectory;

    private final Property<String> materialFactoryClass;

    private TaskProvider<MaterialFactoryTask> materialFactoryTask;

    public TypedMaterialsExtension(Project project) {
        this.project = project;
        ObjectFactory objectFactory = project.getObjects();
        ProjectLayout layout = project.getLayout();

        generatedSourcesDirectory = objectFactory.directoryProperty().convention(
                layout.getBuildDirectory().dir(TypedMaterialsPlugin.DEFAULT_GENERATED_SOURCES_DIR));

        generatedResourcesDirectory = objectFactory.directoryProperty().convention(
                layout.getBuildDirectory().dir(TypedMaterialsPlugin.DEFAULT_GENERATED_RESOURCES_DIR));

        materialFactoryClass = objectFactory.property(String.class);
        materialFactoryClass.set("com.onemillionworlds.typedmaterials.materials.MaterialFactory");
    }

    public void jmeMaterials(){
        librarySearch("jmeCoreMaterials", ".*jme3-core.*", "org.jme3.core.materials");
        librarySearch("jmeEffectsMaterials", ".*jme3-effects.*", "org.jme3.effects.materials");
    }


    /**
     * Registers a task to search for assets in the resources directory(s) of the project and create constants for each one.
     * <p>
     *     Note that if you have resources generated by another task you may need to make the task assetConstants dependant
     *     upon your task that generates the resources.
     * </p>
     *
     *
     * @param fullyQualifiedAssetsClass the fully qualified name of the class will be generated to contains the asset paths. E.g. "com.mygame.assets.Assets"
     */
    public void assetsConstant(String fullyQualifiedAssetsClass){
        String taskName = "assetConstants";
        TaskProvider<AssetConstants> task = project.getTasks().register(taskName, AssetConstants.class, t -> {
            t.setGroup("typedMaterials");
            t.getFullyQualifiedAssetsClass().set(fullyQualifiedAssetsClass);
            t.getOutputSourcesRoot().set(generatedSourcesDirectory.dir(taskName));
        });
        addGeneratedSources(task, AssetConstants::getOutputSourcesRoot);
    }

    /**
     * Registers a task to search for assets in the resources directory(s) of the project and create a flat file for each one.
     * <p>
     *     This file is created in the resources root and is named com.onemillionworlds.typedmaterials.assets.txt. This
     *     enforced naming is to allow the jarAssetConstant task to find the file later.
     * </p>
     *
     * <p>
     *     Note that if you have resources generated by another task you may need to make the task assetConstants dependant
     *     upon your task that generates the resources.
     * </p>
     */
    public void assetsFile(){
        String taskName = "assetsFile";
        TaskProvider<AssetConstants> task = project.getTasks().register(taskName, AssetConstants.class, t -> {
            t.setGroup("typedMaterials");
            t.getOutputResourcesRoot().set(generatedResourcesDirectory.dir(taskName));
        });
        addGeneratedResources(task, AssetConstants::getOutputResourcesRoot);
    }

    /**
     * Registers a task to search for assets in the resources directory(s) of a jar and create a flat file containing the
     * asset locations.
     * <p>
     *     It will also include any local assets
     * </p>
     * <p>
     *     This file is created in the resources root and is named com.onemillionworlds.typedmaterials.assets.txt. This
     *     enforced naming is to allow the jarAssetConstant task to find the file later.
     * </p>
     */
    public void jarAssetsFile(String jarFilterRegex){
        jarAssetsFile(jarFilterRegex, ".*");

    }

    /**
     * Registers a task to search for assets in the resources directory(s) of a jar and create a flat file containing the
     * asset locations.
     * <p>
     *     It will also include any local assets
     * </p>
     * <p>
     *     This file is created in the resources root and is named com.onemillionworlds.typedmaterials.assets.txt. This
     *     enforced naming is to allow the jarAssetConstant task to find the file later.
     * </p>
     */
    public void jarAssetsFile(String jarFilterRegex, String fileRegex){
        String taskName = "assetsFile";
        TaskProvider<AssetConstants> task = project.getTasks().register(taskName, AssetConstants.class, t -> {
            t.setGroup("typedMaterials");
            t.getOutputResourcesRoot().set(generatedResourcesDirectory.dir(taskName));
            t.getJarFilterRegex().set(jarFilterRegex);
            t.getWithinJarFileRegex().set(fileRegex);
            t.getRuntimeClasspath().from(project.getConfigurations().named(JavaPlugin.RUNTIME_CLASSPATH_CONFIGURATION_NAME));
        });
        addGeneratedResources(task, AssetConstants::getOutputResourcesRoot);
    }

    /**
     * Registers a task to search for materials in the jars of the project's runtime classpath
     * @param taskName just a name for the task, needs to be unique
     * @param jarFilterRegex a regex to filter the jars to search for materials. E.g. ".*jme3-core.*" will search
     *                       the core jme library
     * @param outputPackage the package where the generated materials will be placed. E.g. "org.jme3.core.materials"
     */
    public void librarySearch(String taskName, String jarFilterRegex, String outputPackage){
        TaskProvider<TypedJarMaterials> task = project.getTasks().register(taskName, TypedJarMaterials.class, t -> {
            t.setGroup("typedMaterials");
            t.getOutputPackage().set(outputPackage);
            t.getOutputSourcesRoot().set(generatedSourcesDirectory.dir(taskName));
            t.getJarFilterRegex().set(jarFilterRegex);
            t.getRuntimeClasspath().from(project.getConfigurations().named(JavaPlugin.RUNTIME_CLASSPATH_CONFIGURATION_NAME));
        });
        addGeneratedSources(task, TypedJarMaterials::getOutputSourcesRoot);
        getMaterialFactoryTask().configure(factory -> factory.getMaterialRecordFiles().from(task.flatMap(TypedJarMaterials::getBuiltFilesRecordFile)));
    }

    /**
     * Registers a task to search for materials in the standard location of your local project.
     * This function assumes a typical gradle structure, where the materials are in the "src/main/resources/MatDefs" directory.
     *
     * @param outputPackage the package where the generated materials will be placed. E.g. "com.mygame.materials"
     */
    public void localMaterialsSearch(String outputPackage){
        localMaterialsSearch(outputPackage, "src/main/resources/MatDefs", "resources");
    }

    /**
     * Registers a task to search for materials in the given directory of your local project.
     *
     * @param outputPackage the package where the generated materials will be placed. E.g. "com.mygame.materials"
     * @param materialsDirectory the path relative to the module root. E.g. "src/main/resources/MatDefs" or "assets"
     * @param resourcesDirName the name of the resources directory. E.g. "resources" or "assets"
     */
    public void localMaterialsSearch(String outputPackage, String materialsDirectory, String resourcesDirName){
        String taskName = "localTypedMaterials";
        TaskProvider<TypedLocalMaterials> task = project.getTasks().register(taskName, TypedLocalMaterials.class, t -> {
            t.setGroup("typedMaterials");
            t.getInputDirectory().set(project.getLayout().getProjectDirectory().dir(materialsDirectory));
            t.getOutputPackage().set(outputPackage);
            t.getOutputSourcesRoot().set(generatedSourcesDirectory.dir(taskName));
            t.getResourcesDir().set(resourcesDirName);
        });
        addGeneratedSources(task, TypedLocalMaterials::getOutputSourcesRoot);
        getMaterialFactoryTask().configure(factory -> factory.getMaterialRecordFiles().from(task.flatMap(TypedLocalMaterials::getBuiltFilesRecordFile)));
    }

    /**
     * The directory under which generated sources are placed. Each task generates into its own subdirectory (named
     * after the task).
     * Default is "build/generated/sources/typedMaterials"
     */
    public DirectoryProperty getGeneratedSourcesDirectory(){
        return generatedSourcesDirectory;
    }

    /**
     * The directory under which generated resources are placed. Each task generates into its own subdirectory (named
     * after the task).
     * Default is "build/generated/resources/typedMaterials"
     */
    public DirectoryProperty getGeneratedResourcesDirectory(){
        return generatedResourcesDirectory;
    }

    public Property<String> getMaterialFactoryClass(){
        return materialFactoryClass;
    }

    private TaskProvider<MaterialFactoryTask> getMaterialFactoryTask(){
        if(materialFactoryTask == null){
            String taskName = "materialFactory";
            materialFactoryTask = project.getTasks().register(taskName, MaterialFactoryTask.class, task -> {
                task.setGroup("typedMaterials");
                task.getOutputSourcesRoot().set(generatedSourcesDirectory.dir(taskName));
                task.getFullyQualifiedOutputClass().set(materialFactoryClass);
            });
            addGeneratedSources(materialFactoryTask, MaterialFactoryTask::getOutputSourcesRoot);
        }
        return materialFactoryTask;
    }

    /**
     * Adds the task's output directory as a source directory of the main source set (which also makes everything
     * that consumes the main sources depend on the task)
     */
    private <T extends Task> void addGeneratedSources(TaskProvider<T> task, Function<T, DirectoryProperty> outputDirectory){
        project.getPluginManager().withPlugin("java", javaPlugin -> {
            SourceSet mainSourceSet = getMainSourceSet();
            mainSourceSet.getJava().srcDir(task.flatMap(outputDirectory::apply));
            // build scripts commonly replace the source dirs (e.g. `srcDirs += ...`) losing the task dependency, so make
            // sure compilation still depends on the generator
            project.getTasks().named(mainSourceSet.getCompileJavaTaskName()).configure(compile -> compile.dependsOn(task));
        });
    }

    /**
     * Adds the task's output directory as a resource directory of the main source set (which also makes everything
     * that consumes the main resources depend on the task)
     */
    private <T extends Task> void addGeneratedResources(TaskProvider<T> task, Function<T, DirectoryProperty> outputDirectory){
        project.getPluginManager().withPlugin("java", javaPlugin -> {
            SourceSet mainSourceSet = getMainSourceSet();
            mainSourceSet.getResources().srcDir(task.flatMap(outputDirectory::apply));
            // build scripts commonly replace the source dirs (e.g. `srcDirs += ...`) losing the task dependency, so make
            // sure resource processing still depends on the generator
            project.getTasks().named(mainSourceSet.getProcessResourcesTaskName()).configure(process -> process.dependsOn(task));
        });
    }

    private SourceSet getMainSourceSet(){
        return project.getExtensions().getByType(SourceSetContainer.class).getByName(SourceSet.MAIN_SOURCE_SET_NAME);
    }
}
