package com.onemillionworlds.configuration;

import com.onemillionworlds.TypedMaterialsPlugin;
import com.onemillionworlds.tasks.AssetConstants;
import com.onemillionworlds.tasks.MaterialFactoryTask;
import com.onemillionworlds.tasks.TypedJarMaterials;
import com.onemillionworlds.tasks.TypedLocalMaterials;
import org.gradle.api.Project;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.Directory;
import org.gradle.api.model.ObjectFactory;
import org.gradle.api.plugins.JavaPlugin;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.Provider;
import org.gradle.api.tasks.TaskProvider;

@SuppressWarnings("unused")
public class TypedMaterialsExtension{

    private final Project project;

    /**
     * The directory where the generated sources will be placed relative to the module root.
     * Default is "src/main/generatedtypedmaterials/java"
     */
    private final Property<String> generatedSourcesDir;

    /**
     * The directory where the generated resources will be placed relative to the module root.
     * Default is "src/main/generatedtypedmaterials/resources"
     */
    private final Property<String> generatedResourcesDir;

    private final Property<String> materialFactoryClass;

    /**
     * The generated sources directory, carrying the tasks that generate into it (so anything consuming the main
     * source set depends on them)
     */
    private final ConfigurableFileCollection generatedSources;

    /**
     * The generated resources directory, carrying the tasks that generate into it (so anything consuming the main
     * source set depends on them)
     */
    private final ConfigurableFileCollection generatedResources;

    private TaskProvider<MaterialFactoryTask> materialFactoryTask;

    public TypedMaterialsExtension(Project project) {
        this.project = project;
        ObjectFactory objectFactory = project.getObjects();

        generatedSourcesDir = objectFactory.property(String.class);
        generatedSourcesDir.set(TypedMaterialsPlugin.DEFAULT_GENERATED_SOURCES_DIR);

        generatedResourcesDir = objectFactory.property(String.class);
        generatedResourcesDir.set(TypedMaterialsPlugin.DEFAULT_GENERATED_RESOURCES_DIR);

        materialFactoryClass = objectFactory.property(String.class);
        materialFactoryClass.set("com.onemillionworlds.typedmaterials.materials.MaterialFactory");

        generatedSources = objectFactory.fileCollection().from(getGeneratedSourcesDirectory());
        generatedResources = objectFactory.fileCollection().from(getGeneratedResourcesDirectory());
    }

    public void jmeMaterials(){
        librarySearch("jmeCoreMaterials", ".*jme3-core.*", "org.jme3.core.materials");
        librarySearch("jmeEffectsMaterials", ".*jme3-effects.*", "org.jme3.effects.materials");
    }


    /**
     * Registers a task to search for assets in the resources directory(s) of the project and create constants for each one.
     * <p>
     *     Note that if you have resources generated by another task you may need to make the task assetConstants dependant
     *     upon your task that generates the resources.
     * </p>
     *
     *
     * @param fullyQualifiedAssetsClass the fully qualified name of the class will be generated to contains the asset paths. E.g. "com.mygame.assets.Assets"
     */
    @Deprecated
    public void assetConstants(String fullyQualifiedAssetsClass){
        assetsConstant(fullyQualifiedAssetsClass);
    }

    /**
     * Registers a task to search for assets in the resources directory(s) of the project and create constants for each one.
     * <p>
     *     Note that if you have resources generated by another task you may need to make the task assetConstants dependant
     *     upon your task that generates the resources.
     * </p>
     *
     *
     * @param fullyQualifiedAssetsClass the fully qualified name of the class will be generated to contains the asset paths. E.g. "com.mygame.assets.Assets"
     */
    public void assetsConstant(String fullyQualifiedAssetsClass){
        TaskProvider<AssetConstants> task = project.getTasks().register("assetConstants", AssetConstants.class, t -> {
            t.setGroup("typedMaterials");
            t.getFullyQualifiedAssetsClass().set(fullyQualifiedAssetsClass);
            t.getOutputSourcesRoot().set(getGeneratedSourcesDirectory());
        });
        generatedSources.builtBy(task);
    }

    /**
     * Registers a task to search for assets in the resources directory(s) of the project and create a flat file for each one.
     * <p>
     *     This file is created in the resources root and is named com.onemillionworlds.typedmaterials.assets.txt. This
     *     enforced naming is to allow the jarAssetConstant task to find the file later.
     * </p>
     *
     * <p>
     *     Note that if you have resources generated by another task you may need to make the task assetConstants dependant
     *     upon your task that generates the resources.
     * </p>
     */
    public void assetsFile(){
        TaskProvider<AssetConstants> task = project.getTasks().register("assetsFile", AssetConstants.class, t -> {
            t.setGroup("typedMaterials");
            t.getOutputResourcesRoot().set(getGeneratedResourcesDirectory());
        });
        generatedResources.builtBy(task);
    }

    /**
     * Registers a task to search for assets in the resources directory(s) of a jar and create a flat file containing the
     * asset locations.
     * <p>
     *     It will also include any local assets
     * </p>
     * <p>
     *     This file is created in the resources root and is named com.onemillionworlds.typedmaterials.assets.txt. This
     *     enforced naming is to allow the jarAssetConstant task to find the file later.
     * </p>
     */
    public void jarAssetsFile(String jarFilterRegex){
        jarAssetsFile(jarFilterRegex, ".*");

    }

    /**
     * Registers a task to search for assets in the resources directory(s) of a jar and create a flat file containing the
     * asset locations.
     * <p>
     *     It will also include any local assets
     * </p>
     * <p>
     *     This file is created in the resources root and is named com.onemillionworlds.typedmaterials.assets.txt. This
     *     enforced naming is to allow the jarAssetConstant task to find the file later.
     * </p>
     */
    public void jarAssetsFile(String jarFilterRegex, String fileRegex){
        TaskProvider<AssetConstants> task = project.getTasks().register("assetsFile", AssetConstants.class, t -> {
            t.setGroup("typedMaterials");
            t.getOutputResourcesRoot().set(getGeneratedResourcesDirectory());
            t.getJarFilterRegex().set(jarFilterRegex);
            t.getWithinJarFileRegex().set(fileRegex);
            t.getRuntimeClasspath().from(project.getConfigurations().named(JavaPlugin.RUNTIME_CLASSPATH_CONFIGURATION_NAME));
        });
        generatedResources.builtBy(task);
    }

    /**
     * Registers a task to search for materials in the jars of the project's runtime classpath
     * @param taskName just a name for the task, needs to be unique
     * @param jarFilterRegex a regex to filter the jars to search for materials. E.g. ".*jme3-core.*" will search
     *                       the core jme library
     * @param outputPackage the package where the generated materials will be placed. E.g. "org.jme3.core.materials"
     */
    public void librarySearch(String taskName, String jarFilterRegex, String outputPackage){
        TaskProvider<TypedJarMaterials> task = project.getTasks().register(taskName, TypedJarMaterials.class, t -> {
            t.setGroup("typedMaterials");
            t.getOutputPackage().set(outputPackage);
            t.getOutputSourcesRoot().set(getGeneratedSourcesDirectory());
            t.getJarFilterRegex().set(jarFilterRegex);
            t.getRuntimeClasspath().from(project.getConfigurations().named(JavaPlugin.RUNTIME_CLASSPATH_CONFIGURATION_NAME));
        });
        generatedSources.builtBy(task);
        getMaterialFactoryTask().configure(factory -> factory.getMaterialRecordFiles().from(task.flatMap(TypedJarMaterials::getBuiltFilesRecordFile)));
    }

    /**
     * Registers a task to search for materials in the standard location of your local project.
     * This function assumes a typical gradle structure, where the materials are in the "src/main/resources/MatDefs" directory.
     *
     * @param outputPackage the package where the generated materials will be placed. E.g. "com.mygame.materials"
     */
    public void localMaterialsSearch(String outputPackage){
        localMaterialsSearch(outputPackage, "src/main/resources/MatDefs", "resources");
    }

    /**
     * Registers a task to search for materials in the given directory of your local project.
     *
     * @param outputPackage the package where the generated materials will be placed. E.g. "com.mygame.materials"
     * @param materialsDirectory the path relative to the module root. E.g. "src/main/resources/MatDefs" or "assets"
     * @param resourcesDirName the name of the resources directory. E.g. "resources" or "assets"
     */
    public void localMaterialsSearch(String outputPackage, String materialsDirectory, String resourcesDirName){
        TaskProvider<TypedLocalMaterials> task = project.getTasks().register("localTypedMaterials", TypedLocalMaterials.class, t -> {
            t.setGroup("typedMaterials");
            t.getInputDirectory().set(project.getLayout().getProjectDirectory().dir(materialsDirectory));
            t.getOutputPackage().set(outputPackage);
            t.getOutputSourcesRoot().set(getGeneratedSourcesDirectory());
            t.getResourcesDir().set(resourcesDirName);
        });
        generatedSources.builtBy(task);
        getMaterialFactoryTask().configure(factory -> factory.getMaterialRecordFiles().from(task.flatMap(TypedLocalMaterials::getBuiltFilesRecordFile)));
    }

    /**
     * The directory where the generated sources will be placed relative to the module root.
     */
    public Property<String> getGeneratedSourcesDir(){
        return generatedSourcesDir;
    }

    public Property<String> getGeneratedResourcesDir(){
        return generatedResourcesDir;
    }

    public Property<String> getMaterialFactoryClass(){
        return materialFactoryClass;
    }

    /**
     * The resolved directory that generated sources are placed in
     */
    public Provider<Directory> getGeneratedSourcesDirectory(){
        return project.getLayout().getProjectDirectory().dir(generatedSourcesDir);
    }

    /**
     * The resolved directory that generated resources are placed in
     */
    public Provider<Directory> getGeneratedResourcesDirectory(){
        return project.getLayout().getProjectDirectory().dir(generatedResourcesDir);
    }

    /**
     * The generated sources directory as a file collection that knows which tasks generate into it.
     * (Mostly used internally by the plugin)
     */
    public ConfigurableFileCollection getGeneratedSources(){
        return generatedSources;
    }

    /**
     * The generated resources directory as a file collection that knows which tasks generate into it.
     * (Mostly used internally by the plugin)
     */
    public ConfigurableFileCollection getGeneratedResources(){
        return generatedResources;
    }

    private TaskProvider<MaterialFactoryTask> getMaterialFactoryTask(){
        if(materialFactoryTask == null){
            materialFactoryTask = project.getTasks().register("materialFactory", MaterialFactoryTask.class, task -> {
                task.setGroup("typedMaterials");
                task.getOutputSourcesRoot().set(getGeneratedSourcesDirectory());
                task.getFullyQualifiedOutputClass().set(materialFactoryClass);
            });
            generatedSources.builtBy(materialFactoryTask);
        }
        return materialFactoryTask;
    }
}
