/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.onemillionworlds;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TypedMaterialsPluginTest {

}
