package com.onemillionworlds.utilities;

import java.util.List;

public class FactoryBuilder{

    private static final String classTemplate = """
                                     package [PACKAGE];
                                     
                                     import com.jme3.asset.AssetManager;
                                     import com.jme3.material.Material;
                                     import java.util.HashMap;
                                     import java.util.Map;
                                     import java.util.function.Function;
                                     
                                     /**
                                      * AUTOGENERATED CLASS, do not modify
                                      * <p>
                                      * A factory that can create obtain a constructor for a material by its class.
                                      * This is useful for dependency injection and testing purposes
                                      * </p>
                                      */
                                     public class [FACTORY_NAME]{
                                     
                                         public static final [FACTORY_NAME] INSTANCE = new [FACTORY_NAME]();

                                         Map<Class<? extends Material>, Function<AssetManager,Material>> materialMap = new HashMap<>();
                                         
                                         {
                                     [INITIALIZATION]
                                         }
                                     
                                         public [FACTORY_NAME]() {
                                             
                                         }
                                     
                                         @SuppressWarnings("unchecked")
                                         public <T extends Material> T createMaterial(Class<T> materialClass, AssetManager assetManager){
                                             return (T)materialMap.get(materialClass).apply(assetManager);
                                         }
                                    
                                         @SuppressWarnings("unchecked")
                                         public <T extends Material> Function<AssetManager,T> getMaterialConstructor(Class<T> materialClass){
                                             return (Function<AssetManager,T>)materialMap.get(materialClass);
                                         }
                                     
                                     }""";

    public static String createFactoryClassFile(String packageName, String factoryClassName, List<String> fullyQualifiedMaterialClasses){
        StringBuilder initialization = new StringBuilder();

        for (String fullyQualifiedMaterialClass : fullyQualifiedMaterialClasses){
            initialization.append("        materialMap.put(").append(fullyQualifiedMaterialClass).append(".class, assetManager -> new ").append(fullyQualifiedMaterialClass).append("(assetManager));\n");
        }

        return classTemplate
                .replace("[PACKAGE]", packageName)
                .replace("[FACTORY_NAME]", factoryClassName)
                .replace("[INITIALIZATION]", initialization);
    }
}
