name: Stage to maven central without tagging or pushing to gradle plugin portal

on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Decode GPG key
      run: echo "${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}" | base64 --decode > ./secring.gpg

    - name: Create gradle.properties
      run: |
        echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> gradle.properties
        echo "signing.password=${{ secrets.SIGNING_PASSWORD }}" >> gradle.properties
        echo "signing.secretKeyRingFile=/home/runner/work/TypedMaterials/TypedMaterials/secring.gpg" >> gradle.properties
        echo "ossrhUsername=${{ secrets.OSSRH_USERNAME }}" >> gradle.properties
        echo "ossrhPassword=${{ secrets.OSSRH_PASSWORD }}" >> gradle.properties

    - name: Publish package
      run: ./gradlew publishMavenJavaPublicationToSonaTypeRepository